version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    open-pull-requests-limit: 2
    groups:
      # Group all patch and minor updates together
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      # Group major version updates separately
      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"
