services:
  postgres:
    image: postgres:17
    container_name: postgres-iterate
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iterate
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d iterate"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
