packages:
  - apps/*
  - packages/*
  - estates/*
  - estates/*/apps/*
  - vibe-rules

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - drizzle-kit
  - miniflare
  - wrangler
  - better-wait-until
  - '@cloudflare/sandbox'
  - alchemy

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - workerd
