packages:
  - apps/*
  - packages/*
  - estates/*
  - estates/*/apps/*
  - vibe-rules

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - workerd
