name: Build and Push Sandbox Container

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-push:
    runs-on: "${{ github.repository_owner == 'iterate-com' && 'depot-ubuntu-24.04-arm-4' || 'ubuntu-24.04' }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v2

      - name: Setup Doppler
        run: doppler setup --config 'prd' --project os
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

      - name: Enable QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate version
        id: version
        run: echo "VERSION=$(date +'%d%m%y%H%M')" >> $GITHUB_OUTPUT

      - name: Build and push container
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
        run: |
          cd apps/os/backend/sandbox
          docker build --platform linux/amd64 -t sandbox:${{ steps.version.outputs.VERSION }} .
          cd ../..
          doppler run -- pnpx wrangler containers push sandbox:${{ steps.version.outputs.VERSION }}

      - name: Update wrangler.jsonc with new version
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          sed -i 's|"image": "registry.cloudflare.com/04b3b57291ef2626c6a8daa9d47065a7/sandbox:[^"]*"|"image": "registry.cloudflare.com/04b3b57291ef2626c6a8daa9d47065a7/sandbox:'$VERSION'"|g' apps/os/wrangler.jsonc
          git add apps/os/wrangler.jsonc

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update sandbox container to version ${{ steps.version.outputs.VERSION }}"
          branch: update-sandbox-${{ steps.version.outputs.VERSION }}
          title: "Update sandbox container to version ${{ steps.version.outputs.VERSION }}"
          body: |
            This PR updates the sandbox container image to version `${{ steps.version.outputs.VERSION }}`.

            The container has been built and pushed to the Cloudflare registry.

            Changes:
            - Built new sandbox container with platform `linux/amd64`
            - Pushed to registry as `sandbox:${{ steps.version.outputs.VERSION }}`
            - Updated `wrangler.jsonc` to reference the new version
          add-paths: |
            apps/os/wrangler.jsonc
