name: Claude Auto Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  claude-review:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Setup pnpm via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@$(node -p "require('./package.json').packageManager.split('@')[1]") --activate

      - name: Install dependencies
        run: pnpm install

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3

      - name: Fetch secrets from Doppler
        id: doppler
        run: |
          echo "ANTHROPIC_API_KEY=$(doppler secrets get ANTHROPIC_API_KEY --plain)" >> $GITHUB_OUTPUT
        env:
          DOPPLER_TOKEN: ${{ secrets.CLAUDE_DOPPLER_TOKEN }}

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ steps.doppler.outputs.ANTHROPIC_API_KEY }}
          settings: |
            {
              "env": {
                "DOPPLER_TOKEN": "${{ secrets.CLAUDE_DOPPLER_TOKEN }}"
              }
            }
          prompt: |
            Review this PR for security issues, bugs, and code quality. 
            Proactively fix unchecked type casts, or unfixable linter issues.

            Environment setup:
            - Node.js v24 and pnpm v9 are available
            - DOPPLER_TOKEN is set in the environment for accessing secrets
            - You can run: pnpm test, pnpm lint, pnpm typecheck, etc.

            ## Code Quality
            - Follow our coding standards
            - No unchecked type casts, unless unavoidable

            ## Testing
            - Unit tests for new functions
            - Regression tests for bug fixes
            - Edge cases covered

            ## Security
            - No hardcoded credentials
            - Input validation implemented
            - Proper error handling
            - No sensitive data in logs

          claude_args: |
            --model claude-sonnet-4-5-20250929
            --allowedTools "Bash(pnpm i),Bash(pnpm test:*),Bash(pnpm eval:*),Bash(pnpm lint),Bash(pnpm typecheck),Bash(pnpm clean),Bash(pnpm dev)"
