name: Deploy to Cloudflare
on:
  push:
    branches: [main]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    #Skip for now
    if: false
    runs-on: "${{ github.repository_owner == 'iterate-com' && 'depot-ubuntu-24.04-arm-4' || 'ubuntu-24.04' }}"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install
      - name: Install Doppler CLI
        run: curl -Ls https://cli.doppler.com/install.sh | sh
      - name: Deploy
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
        run: doppler run --token $DOPPLER_TOKEN --project os-v2 --config prd -- pnpm deploy
        working-directory: apps/platform
